logging:
    level:
        org:
            hibernate:
                SQL: debug
server:
    port: 8080
spring:
    datasource:
        password: ''
        url: jdbc:h2:mem:test;DB_CLOSE_DELAY=-1
        username: sa
    h2:
        console:
            enabled: true
            path: /h2-console
    jpa:
        hibernate:
            ddl-auto: none
        open-in-view: false
    sql:
        init:
            mode: always
            schema-locations: classpath:db/quartz_tables_h2.sql
